In [1]:
import os
print(os.getcwd())

C:\Users\silpa\OneDrive\Desktop\AIML

!pip install pandas

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\silpa\appdata\local\programs\python\python310\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\users\silpa\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\silpa\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\silpa\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\silpa\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\silpa\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [6]:
data=pd.Series([10,23,43,65])
print(data)

0    10
1    23
2    43
3    65
dtype: int64

In [7]:
s=pd.DataFrame({'name':["Alice","Bob","John"],'age':[30,25,34],'score':[34,67,89]})
print(s)

    name  age  score
0  Alice   30     34
1    Bob   25     67
2   John   34     89

In [8]:
lst=[['Alice',25],['Bob',30]]
df=pd.DataFrame(lst,columns=['Name','Age'])

In [9]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes

In [12]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [13]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: object

In [14]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [15]:
df.loc()

In [16]:
df.iloc()

In [17]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [18]:
df['Gender']=['F','M']
df.drop('Gender',axis=1, inplace=True)

In [19]:
df.isnull()

    Name    Age
0  False  False
1  False  False

In [20]:
df.dropna()

    Name  Age
0  Alice   25
1    Bob   30

In [21]:
df.fillna(0)

    Name  Age
0  Alice   25
1    Bob   30

In [22]:
df['Age'] = [25, 30]
print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [23]:

df.groupby('Name')['Age'].mean()

Name
Alice    25.0
Bob      30.0
Name: Age, dtype: float64

In [24]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})
df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Marks': [85, 90, 78]
})
pd.merge(df1, df2, on='ID')

   ID     Name  Marks
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     78

In [25]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie']
})
df2 = pd.DataFrame({
    'Marks': [85, 90, 78]
})
df1.join(df2)

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78

In [26]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\silpa\OneDrive\Desktop\AIML
['.ipynb_checkpoints', 'array.npy', 'Untitled.ipynb', 'Untitled1.ipynb']

In [28]:
import pandas as pd
data={
    'name':['Alice','Bob','Charlie'],
    'mark':[85,90,78]
}
df=pd.DataFrame(data)
df.to_csv('output.csv',index=False)
print("output.csv created")

output.csv created

In [29]:
import os
print(os.path.exists('output.csv'))

True

In [30]:
df=pd.read_csv('output.csv')
print(df)

      name  mark
0    Alice    85
1      Bob    90
2  Charlie    78

In [32]:
df.sort_values('mark')

      name  mark
2  Charlie    78
0    Alice    85
1      Bob    90

In [33]:
df['mark'].apply(lambda x: x+1)

0    86
1    91
2    79
Name: mark, dtype: int64

In [35]:
df['name'].unique()

array(['Alice', 'Bob', 'Charlie'], dtype=object)

In [37]:
df['mark'].value_counts()

mark
85    1
90    1
78    1
Name: count, dtype: int64